---
- hosts: all
  become: yes
  tasks:
    - name: add elastic apt repository signing keys
      apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: add elastic apt repositories
      apt_repository: repo="deb https://artifacts.elastic.co/packages/5.x/apt stable main" update_cache=yes

    - name: install elasticsearch package
      apt: name=elasticsearch

    - name: install java runtime executable
      apt: name=default-jre
